pipeline {
    agent any

    environment {
        POM_VERSION = ""
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven'
                    args '-v /root/.m2:/root/.m2' // Monta o diretório .m2 do host para acelerar builds subsequentes
                }
            }
            steps {
                script {
                    sh "mvn package -Dmaven.test.skip=true"
                    pom = readMavenPom file: 'pom.xml'
                    POM_VERSION = pom.version
                }
                stash name: 'source', includes: 'target/**' // Arquiva apenas a pasta 'target'
            }
        }

        stage('Apply Kubernetes files') {
            environment {
                KUBECONFIG = '/root/.kube/config' // Define o local do arquivo kubeconfig
            }
            steps {
                sh 'kubectl apply -f teste'
                sh 'kubectl rollout restart deployment cleiton-api'
            }
        }
    }
}
